### ISSUE TITLE
Hello,I need some help,if you can give it to me!

### ISSUE THREAD

**Issue by SimpleCold** [Josko/aura-bot#26]
How can convert your x64 compatible BNCSutil to one compatible with the vanilla ghost++?
It gives me a ton of errors,if I try to compile the one with ghost++ for x64.
I really need some functionality from the vanilla one.

**Comment by Josko** [comment]
You will need to add a new configuration for ghost++ to build as x64 and link against built x64 BNCSutil and StormLib. If you could pastebin or similar your build log I'd be happy to help.

Also consider if it would be easier to port over the functionality.

**Comment by SimpleCold** [comment]
Thanks for your reply,here is the whole solution and boost libs,unzip them in C:\ or D:\ root.
It seems that ghost project already builds in 64,the bncsutil is the problem.
http://www.mediafire.com/download/5abx1adrtnazvq5/boostlibs.7z
http://www.mediafire.com/download/2rtp1ic36rx0l1k/GHSX.7z

**Comment by Josko** [comment]
Well, when I downloaded your project I noticed your bncsutil is not the one from this project so of course it won't link. I made multiple changes to bncsutil so it can compile for x64 on Windows. How about you try to remove default bncsutil and just replace it with mine and then try to build?

**Comment by SimpleCold** [comment]
Hello, this is what I receive from VS when trying to compile.
http://pastebin.com/75Pb94KM

**Comment by SimpleCold** [comment]
Actually, I have a more pressing matter, original bot cannot load one certain map through !map command(cannot extract war3map.j), when your bot can do it.
Possible ways for fixing,please?

**Comment by Josko** [comment]
That is because aura-bot uses a much newer StormLib version.I also remember the aura-bot supplied one has a few of my modifications as well but I can't remember which on top of my head.

So fixing would mean replacing your StormLib with the one used in aura-bot - similar to the BNCSutil story.
