### ISSUE TITLE
Hello, it's me again!

### ISSUE THREAD

**Issue by SimpleCold** [Josko/aura-bot#30]
The problem is, I can't get my almost vanilla version (+gcbi patch) to compile on VS 2015( I've updated the boost toolset,too), while it perfectly compiles on 2013, it gives about 200 errors about redefinitions, from what I googled, it is a conflict with included almost everywhere ms_stdin.h/stdin.h, I've managed to go down to 14 errors, by commenting out some of those but can't deal with them completely, which makes me very sad.
Since you updated your own to 2015, I hope maybe you can help, or at least show the way where to dig for the solution, more so because it does not look connected to the boost libraries.

**Comment by Josko** [comment]
I am sorry but I cannot help with other projects. Especially not in the issues of this one. The commit history is public and all of the files too, so you can compare to my changes/files and try to fix it like that. Good luck!
