### ISSUE TITLE
How do I host the same game on multiple realms?

### ISSUE THREAD

**Issue by Meai** [Josko/aura-bot#33]
Other hosting bots can do that, I have not seen any reference to how to do that with aura-bot?
I want people from USEAST to join a game made on EUROPE

**Comment by Meai** [comment]
apparently you just have to add a second bnet server and then it will use that one for the same game

**Comment by Meai1** [comment]
i forgot how I did that... dont know anymore how to config that

**Comment by Meai1** [comment]
ok, have to add sections like this: 

bnet_server blabla

then entire same thing with:

bnet2_server blablaBLA
