### ISSUE TITLE
New patch 1.27b

### ISSUE THREAD

**Issue by luciouskami** [Josko/aura-bot#39]
Since BZ has updted war3 again,now the current war3 version is 1.27b(1.27.1.7085).If it is need to change aura.cfg,how can I get the "exeversion" and the "exeversionhash"?

**Comment by Josko** [comment]
I haven't tried it yet but I'd first try with version still = 27, and leaving the exeversion* fields empty. If that doesn't work I can explain how to fetch them via Wireshark.

**Comment by luciouskami** [comment]
I've download Wireshark.
I guess the step like this:
1. Open Wireshark and set a new capture rule named wae3: port 6112(my war3 game port).
2.Start a LAN game
3.Capture and wait its print.

I got a packet like this:
Data: f7307f00505833571b00000001000000c1320000576f726c...
Is that right?

**Comment by luciouskami** [comment]
@Josko 
27 works well,leaving the exeversion* fields empty is ok.
It seems we doesn't need updated it.
Thank you.

**Comment by Josko** [comment]
That's even better! But yeah ultimately you'd be just getting part of the data from a packet during login. Maybe next patch :+1:
