### ISSUE TITLE
Bug: Cant find game.dll although path is correct

### ISSUE THREAD

**Issue by Meai1** [Josko/aura-bot#43]
Reason: They apparently renamed it to 'Game.dll' (=UPPER case)

Solution: Make your code ignore the case. 

Current workaround: I can rename the dll, seems to still work.

P.S: Same thing for the extracted Blizzard.j -> blizzard.j

btw. I always have to put the blizzard.j etc. into the War3Patch.mpq manually, they arent there by default (anymore?)

**Comment by Josko** [comment]
Thanks for reporting. Going to make it find the right filename so it works on both case-sensitive and case-insensitive file systems.

**Comment by Josko** [comment]
Hey, should be fixed in the master branch right now. For script files I'll extract that into a new ticket as it's not directly related.
