### ISSUE TITLE
Can't change bot to RoC

### ISSUE THREAD

**Issue by KappaFrappa** [Josko/aura-bot#46]

**Comment by Josko** [comment]
Hey, only with the configuration no as this was removed - I thought at the time no one plays RoC. To make it work. you would have to backport the code but it's a pretty/easy small task.

AFAIK what needs to be changed is the login (in SEND_SID_AUTH_INFO you don't send the TFT key, etc.) and in the SEND_W3GS_GAMEINFO packet advertise the game as RoC and not TFT.

Example of what you need to do, but not literally everything (random ghost-bot based repo taken):
https://github.com/zenithtekla/G-hostOne/search?utf8=%E2%9C%93&q=m_TFT&type=
