### ISSUE TITLE
Bot on ubuntu vps say "Segmentation fault (core dumped)" after description

### ISSUE THREAD

**Issue by klincheR** [Josko/aura-bot#47]
>  [AURA] started loading [ip-to-country.csv]
> [AURA] iptocountry data: 10% loaded
> [AURA] iptocountry data: 20% loaded
> [AURA] iptocountry data: 30% loaded
> [AURA] iptocountry data: 40% loaded
> [AURA] iptocountry data: 50% loaded
> [AURA] iptocountry data: 60% loaded
> [AURA] iptocountry data: 70% loaded
> [AURA] iptocountry data: 80% loaded
> [AURA] iptocountry data: 90% loaded
> [AURA] iptocountry data: 100% loaded
> [AURA] finished loading [ip-to-country.csv]
> [BNET: Euro] connecting to server [europe.battle.net] on port 6112
> [BNET: Euro] resolved and cached server IP address 5.42.181.16
> [BNET: Euro] connected
> Segmentation fault (core dumped)

**Comment by klincheR** [comment]
if you need more information you can mail me klinchery@gmail.com

**Comment by Josko** [comment]
Well a few questions arise here, as the current master works and does not crash.

1.  Which version are you using? Version or commit or approx. age?
2.  Did you recompile and install the aura-bot version of BNCSUtil? There were at least some compiler/linker switch changes that could account for the crash.
3.  Which version of Ubuntu?
4.  Which compiler and which version is it?

Crashes just when it should send the AUTH to BNet:

>[AURA] finished loading [ip-to-country.csv]
>[BNET: Northrend] connecting to server [europe.battle.net] on port 6112
>[BNET: Northrend] resolved and cached server IP address 5.42.181.15
>[IRC: irc.quakenet.org] connecting to server [irc.quakenet.org] on port 6667
>**[BNET: Northrend] connected**
>[IRC: irc.quakenet.org] connected
>[IRC: irc.quakenet.org] NOTICE AUTH :*** Looking up your hostname
>[IRC: irc.quakenet.org] NOTICE AUTH :*** Checking Ident
> **[BNET: Northrend] attempting to auth as Warcraft III: The Frozen Throne**
>[IRC: irc.quakenet.org] NOTICE AUTH :*** Found your hostname
>[BNET: Northrend] cd keys accepted

**Comment by klincheR** [comment]
using the newest version on a fresh ubuntu 16.04 vps i followed the readme
and only had some problems with some packages but i could read from the
errors which packages i missed after that it compiled with no problem.
After i uploaded the storm.dll game.dll and the w3.exe it threw that error.

2017-08-04 16:20 GMT+02:00 Joško Nikolić <notifications@github.com>:

**Comment by klincheR** [comment]
so i just rebuild from master after deleting everything besided cfg and folder with wc3 files. this is what happened on first boot try the error came up just after `[BNET: Euro] connecting to server [europe.battle.net] on port 6112
[BNET: Euro] resolved and cached server IP address 5.42.181.14
[BNET: Euro] connected
` this part. heres the [error ](https://pastebin.com/d0EwRLDy)

**Comment by Josko** [comment]
I'll try it out on a fresh Ubuntu 16.04 VM and see how it goes. From the stacktrace it seems some std::string::append() failed from concating to a std::string...

**Comment by Josko** [comment]
Btw. One cause could be a StormLib bug so when compiling it try instead of:

`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DYNAMIC_MODULE=1 ..`

this invocation:

`cmake -DBUILD_DYNAMIC_MODULE=1 ..`

**Comment by klincheR** [comment]
gonna start all over 👍 lets see if it helps

**Comment by ThomayMayo** [comment]
Getting the same error on latest commit on OS X:

> [AURA] finished loading [ip-to-country.csv]
> [BNET: USWest] connecting to server [uswest.battle.net] on port 6112
> [BNET: USWest] resolved and cached server IP address 12.129.236.17
> [BNET: Europe] connecting to server [europe.battle.net] on port 6112
> [BNET: Europe] resolved and cached server IP address 5.42.181.17
> [BNET: USEast] connecting to server [useast.battle.net] on port 6112
> [BNET: USEast] resolved and cached server IP address 199.108.55.54
> [BNET: Asia] connecting to server [asia.battle.net] on port 6112
> [BNET: Asia] resolved and cached server IP address 121.254.164.34
> [BNET: Europe] connected
> [BNET: USEast] connected
> [BNET: USWest] connected
> Segmentation fault: 11

Worked fine with a version from approx. 3 weeks ago. I'm using latest stormlib from brew.

**Comment by Josko** [comment]
This should be fixed now - at least it is working reliably on my Windows box at the moment. Reopen if still persistent.
