### ISSUE TITLE
Current list of commands

### ISSUE THREAD

**Issue by ThomayMayo** [Josko/aura-bot#48]
README states `More commands added either ingame or bnet`

Is there a list of the current commands?

**Comment by Josko** [comment]
This was actually done many years ago but then the practice stopped. Only way now would be to check it in the source code itself: [BNET](https://github.com/Josko/aura-bot/blob/master/src/bnet.cpp#L584) and [GAME](https://github.com/Josko/aura-bot/blob/master/src/game.cpp#L1658) - commands start right under the `switch (CommandHash)` line.
