### ISSUE TITLE
Show error to user when map cannot be loaded

### ISSUE THREAD

**Issue by Frotty** [Josko/aura-bot#54]
When you type 
`!map someName`
and the bot tries to load the map but fails, it only shows an error on the console, but not to the user.
It is hard to tell whether there actually was an error since there is no reaction from the bot.

Also maybe add a hint that such an "invalid mapfile" error can be caused by missing permissions, or have actually 2 different errors, one for "unable to access" and one "invalid file".

**Comment by Josko** [comment]
> 2017-12-18 20:14:14	@josko	!map troll
> 2017-12-18 20:14:14	+Aura	Loading map file [troll.w3x]
> 2017-12-18 20:14:14	+Aura	Error while loading map: [invalid map_size detected]

Is this OK?

**Comment by Frotty** [comment]
Yes, looks great 👍
