### ISSUE TITLE
A few questions/issues

### ISSUE THREAD

**Issue by CookiePl0x** [Josko/aura-bot#62]
Hello!

I tried out your bot and am having a few issues so I would like to ask some questions if that would be okay. I used the bot on battle.net as well as eurobattle, on battle.net I have the problem thought that I occassionally get socket errors on all realms and the bot becomes unable to reconnect. Is this due to the missing BNLS?

Second, is there a way to disable the gameover timer or do I have to recompile it? it doesn't help at all when you are playing games like RPGs for example and suddenly remaining player disconnects because someone leaves.

Is there a way to have messages displayed in chat/battle.net? For example when I'm trying to host and the gamename is already taken, then it won't say anything but in the console you will see that the gamename is already in use.

And my last question, would it be possible to implement Discord? Or is it very difficult? It's far more popular for gaming I think and thus having it there would only be beneficial, but perhaps I'm wrong. Just asking out of curiosity.

Thank you in advance for reading and hopefully replying! :)

**Comment by Josko** [comment]
Hi!

It _happens_ that the connection fails - some console output when this happens could help. I frequently let the bot idle like this to see if some problems occur but it always pretty much reconnects in a timely fashion. Is the socket error in question perhaps `ECONNRESET`?

Regarding gameover timer: Currently it is hardcoded to 60 seconds. Disabling it would mean any games with just 1 player would persist that game forever until they leave or someone manually ends it - so a "general" setting for it would not suffice (people or malicious bots joining and AFKing). Proper way would be to have it on a per "map" basis (e.g. `map_min_players = 2`). This is doable only via .cfg file - would you be fine with that? Alternatively, a current workaround would be to add at least 1 fake player via `!fp` which cancels the timer and the game ends when the last real player leaves.

The bot does say something - but only in the non-existing lobby. It has to rejoin the channel before it could say something in the channel which happens at a later point in time. Proper way would be to send a whisper to the creator of the game. Would that be O.K.? Example what currently happens:
> [BNET: Northrend] startadvex3 failed
> [GAME: Azeroth wars RP] Unable to create game on server [europe.battle.net]. Try another name
> [AURA] deleting current game [Azeroth wars RP]
> [BNET: Northrend] joining channel [doktors]

With regards to Discord: I didn't see a mature C/C++ API to make use of. Unfortunately I don't use the service so I'm not keen on investing time on it (but patches are welcome).

**Comment by CookiePl0x** [comment]
Thanks for getting back to me!

I don't think there were any log files, are there? I will leave the bot running again since I temporarily switched back to regular GHost++. I'm not sure if it was that but I think it was, it happens to all realms at the same time and the bot also already became unable to reconnect for a bit like those temporary IP bans.

60 seconds? When I start a game by myself it finishes instantly and I think it happened to my friend as well after I left a game once (need to verify this first). For me a general setting to turn it completely off would be fine since we are mostly playing in private, we have over 50 RPG maps on the bot. Having to create a .cfg for each map currently and those that I will add in the future, doesn't sound like a very viable solution. In my experience people usually also don't use fakeplayers when there are at least 2 real players and for RPGs for example there is no point in having them end when there is only one person left.

I see... so it sends the message to the lobby? Why not to the chat afterwards? A whisper would of course be fine as well, as long as the creator knows that the gamename is in use and isn't just wondering what is going on with the game.

I understand, I was just curious what you think of it, I know a bit of coding but not enough to make something happen, probably. I Might take a proper look at the C++ libraries for discord bots at a point.

There was also something strange that happened twice, the game started to lag for everyone and the message in the console was uhm, I really should have screenshotted it, something like last update was late by 10000ms. I'm not sure what was causing this, I had a continous ping test running to the VPS while it happened and didn't notice a spike or anything.

**Comment by Argon-** [comment]
Mind you, most of the RPG maps I know do not allow a single player to play alone. They end the game on their own. So when it ends instantly, this mind be an indication for that. Just guessing though.

**Comment by CookiePl0x** [comment]
Those are a few popular English RPGs. Almost no Korean map has that, and there is no real point in doing that either since you could always just use fakeplayer.exe if you wanted to cheat or use multiclient.

**Comment by Argon-** [comment]
Why would I play Korean maps though.
Regarding fakeplayers, there are actually maps attempting detection of that (and various other cheats). Not sure how reliably though. In the end, it's always a game of cat-and-mouse.

**Comment by CookiePl0x** [comment]
More maps to play, better made than most English RPGs. Are there? I haven't come across those yet. Though I think instead of looking at single player, we should look more at multiplayer, all of the maps allow you to continue playing when everyone else has left.

**Comment by Josko** [comment]
> There was also something strange that happened twice, the game started to lag for everyone and the message in the console was uhm, I really should have screenshotted it, something like last update was late by 10000ms. I'm not sure what was causing this, I had a continous ping test running to the VPS while it happened and didn't notice a spike or anything.

Forgot to reply to this... Considering 10000ms is 10 seconds which is a lot of processing power, my best guesses are:

- the VPS had some CPU bound usage spike,
- all of the players are using GProxy++ which is not horribly efficient,
- you have a lot of games running simultaneously,
- added a feature like replay saving which the exactly reason this message was added in GHost++ in the first place,
- bug...
- all or some of the above.

**Comment by CookiePl0x** [comment]
Seeing how I was the only person with GProxy and it was the only game running, I would say there was a possible CPU spike unless it's a bug. Will monitor and let you know in case I notice anything specific.

**Comment by Josko** [comment]
OK, open an another issue regarding performance when it occurs again.

Whisper to game creator & configurable game over player number have been implemented:

In your aura.cfg:

```
### the game over timer will start when this number of human players in a game has been reached. default value is 1.

bot_gameoverplayernumber = 1
```
