### ISSUE TITLE
Can't compile in VS2015 Windows

### ISSUE THREAD

**Issue by juvian** [Josko/aura-bot#75]
Stormlib compiles fine, but BNCSutil, a lot of errors appear, most of which caused by undefined types:

![image](https://user-images.githubusercontent.com/5660396/38938330-a5704888-42fb-11e8-8653-00fa4571d0fc.png)

**Comment by JFGHT** [comment]
Try this https://github.com/Josko/aura-bot/issues/69#issuecomment-381062960 .

**Comment by juvian** [comment]
Tried that but same result. Tried the same later with VS2017 and it worked, just never managed with VS2015
