### ISSUE TITLE
Can’t create a game!

### ISSUE THREAD

**Issue by HelloWorldAndEveryone** [Josko/aura-bot#78]
Hello. I configured the bot and map, bot successfully join to the channel (ozbnet) but when I write !priv or !pub gamename and follow bot by name, I see game in list but when I press this there is no parameters. No map, no descripton, nothing... 

Btw, ghost one host this map on this pvpgn server successfully

**Comment by HelloWorldAndEveryone** [comment]
![screenshot_1](https://user-images.githubusercontent.com/39007356/39671004-1703d19c-5119-11e8-97a4-5e2320863571.png)
There is a preview how it's bugging!

**Comment by juvian** [comment]
Check https://github.com/Josko/aura-bot/issues/72

**Comment by HelloWorldAndEveryone** [comment]
This doesn't help me :( ... Still getting same, I'm using War3 1.26

**Comment by juvian** [comment]
Try running bot from command and redirect ouput to a file and post it

![image](https://user-images.githubusercontent.com/5660396/39715649-5cc7d55c-5204-11e8-96d7-72915c97a186.png)

**Comment by HelloWorldAndEveryone** [comment]
[log.txt](https://github.com/Josko/aura-bot/files/1980863/log.txt)

All right there, idk why it doesn't working..

**Comment by juvian** [comment]
I will try hosting there tomorrow

**Comment by HelloWorldAndEveryone** [comment]
Where are you hosting?

**Comment by juvian** [comment]
Have hosted both on official bnet (1.28) and eurobattle (1.28)

**Comment by HelloWorldAndEveryone** [comment]
Maybe Josko also made things for 1.28 and bot stopped working on 1.26

**Comment by HelloWorldAndEveryone** [comment]
By the way, Rolling Release too doesn't work for me! Author made crash-commits before 27 Dec so...

**Comment by juvian** [comment]
Release on w32 works fine for me on VS2017

**Comment by juvian** [comment]
I mean compiling aura works, will try 1.26 tomorrow

**Comment by HelloWorldAndEveryone** [comment]
Compiling works, of course:) It worked always, but map doesn't show in the game...

**Comment by juvian** [comment]
Getting version is too old with this configuration, you know the right one?

 bnet3_server = pvpgn.onligamez.ru
 bnet3_serveralias = onligamez
 bnet3_cdkeyroc = FFFFFFFFFFFFFFFFFFFFFFFFFF
 bnet3_cdkeytft = FFFFFFFFFFFFFFFFFFFFFFFFFF
 bnet3_locale = system
 bnet3_username = juvian
 bnet3_password = xxxxx
 bnet3_firstchannel = The Void
 bnet3_rootadmins = juvian
 bnet3_commandtrigger = !
 bnet3_custom_war3version = 26
 bnet3_custom_exeversion = 1 0 26 1
 bnet3_custom_exeversionhash = 194 206 231 242  
 bnet3_custom_passwordhashtype = pvpgn
 bnet3_custom_pvpgnrealmname = PvPGN Realm

**Comment by HelloWorldAndEveryone** [comment]
bnet_server = pvpgn.onligamez.ru
bnet_serveralias = OZ
bnet_cdkeyroc = FFFFFFFFFFFFFFFFFFFFFFFFFF
bnet_cdkeytft = FFFFFFFFFFFFFFFFFFFFFFFFFF
bnet_locale = system
bnet_username = BestBotEver
bnet_password = 555555
bnet_firstchannel = The Void
bnet_rootadmins = VMS_NoNaMe
bnet_commandtrigger = !
bnet_custom_war3version = 26
bnet_custom_exeversion = 
bnet_custom_exeversionhash = 
bnet_custom_passwordhashtype = pvpgn
bnet_custom_pvpgnrealmname = PvPGN Realm


this right

**Comment by juvian** [comment]
Same as me then, guess I will have to install 1.26 and try without setting hash manually

**Comment by juvian** [comment]
Well, when I log in through w3, it always says account does not exist and can't create new one 😭

**Comment by AnImperialMan** [comment]
Did u install https://forum.onligamez.ru/resources/pvpgn-server-dlja-warcraft-3-ozbnet.89/
this client?
But it's on russian, 

1.Firstly press this 
![image](https://user-images.githubusercontent.com/29813338/39801457-edfbbc76-5373-11e8-9129-b53da9f5dd25.png)
2.Unpack to any-folder
3.Download and apply reg or vbs file
![image](https://user-images.githubusercontent.com/29813338/39801471-f8ad1caa-5373-11e8-8cbc-0f4d59fbbaf6.png)
4.Run BNProxy.exe
Then you need create 2 accounts. One for bot, one for yourself. U can write any nick and any password, and any email(or use dropmemail) it won't ask acception for you

**Comment by HelloWorldAndEveryone** [comment]
Did u install https://forum.onligamez.ru/resources/pvpgn-server-dlja-warcraft-3-ozbnet.89/
this client (oz-games)? For working it you need also war1.26 frozen throne(u can download it anywhere it's free)
But it's on russian,

1.Firstly press this
![image](https://user-images.githubusercontent.com/39007356/39803594-15cd36de-537a-11e8-8a3f-b605d3b5abe1.png)
2.Unpack to any-folder
3.Download and apply reg or vbs file
![image](https://user-images.githubusercontent.com/39007356/39803607-2619b5d0-537a-11e8-9d69-3855f58f5dea.png)

4.Run BNProxy.exe
Then you need create 2 accounts. One for bot, one for yourself. U can write any nick and any password, and any email(or use dropmemail) it won't ask acception for you

**Comment by juvian** [comment]
I just tried using the 1.26 w3 I have for iccup. Have you tried hosting with ghost?

**Comment by AnImperialMan** [comment]
With ghost is working. With aura-bot no

**Comment by juvian** [comment]
![image](https://user-images.githubusercontent.com/5660396/39848455-73c91c7c-53dd-11e8-923e-28e77976d92d.png)

**Comment by HelloWorldAndEveryone** [comment]
Did u
1.Run reg or vbs files?
2.Pick war3 1.26 folder?

I don't know china language so don't understand what is written there :(

**Comment by HelloWorldAndEveryone** [comment]
Idk this language, maybe Korean XD

**Comment by HelloWorldAndEveryone** [comment]
Try with any other pvpgn server on war1.26

**Comment by juvian** [comment]
Don't know any other lol. Just iccup but don't know ip and such

**Comment by HelloWorldAndEveryone** [comment]
I found good server for your testings!
1)Download this https://yadi.sk/d/eno7pL3D3H9ZWj (War3 1.26 + Client to the server)
2)Unpack to disk C (only to disk C because reg file need this path "C:\\WarcraftIII 1.26a"
3)Apply footyFix3.reg from the folder (or if you don't want to unpack to disk C, change InstallPath, and unpack to this Path)
4)Create account for bot (any nickname and password, any email)
5)Create account for you
6)Try to run bot using these settings:
bnet_server = 195.88.208.82
bnet_serveralias = Crazy Server
bnet_cdkeyroc = FFFFFFFFFFFFFFFFFFFFFFFFFF
bnet_cdkeytft = FFFFFFFFFFFFFFFFFFFFFFFFFF
bnet_locale = system
bnet_username = # Edit This
bnet_password = # Edit This
bnet_firstchannel = Footman Channel
bnet_rootadmins = # Edit This
bnet_commandtrigger = !
bnet_custom_war3version = 26
bnet_custom_exeversion =  1 0 26 1
bnet_custom_exeversionhash = 194 206 231 242 
bnet_custom_passwordhashtype = pvpgn
bnet_custom_pvpgnrealmname = PvPGN Realm

7)Try to create a game
8)Try to join the game

Here is the full instuction for you:) I hope it will work...

**Comment by juvian** [comment]
Hosted perfectly, so you either didn't make the necessary changes I mentioned or that server requires weird stuff. 
[aura.zip](https://github.com/Josko/aura-bot/files/1996200/aura.zip)

Try with that exe which is the one Im using

**Comment by HelloWorldAndEveryone** [comment]
Don't working, so strange... Can you give ur cfg file, your map and your map cfg?

**Comment by HelloWorldAndEveryone** [comment]
Btw, maybe u mean wrong? I too can host it but I can't join the game.(don't see map preview etc), can you?

**Comment by juvian** [comment]
I could join game. Did you try on your server on in Crazy Server? I used standard map (12)EmeraldGardens.w3x. Don't have config, used !map gardens and then !pub test

**Comment by HelloWorldAndEveryone** [comment]
In CrazyServer

**Comment by HelloWorldAndEveryone** [comment]
I configured it in relative ways. Map in /maps
warcraft3 files in war3
I did this for being able to launch the bot on VPS. Try with relative please.

**Comment by juvian** [comment]
Do you use discord? Would be easier to talk there

**Comment by HelloWorldAndEveryone** [comment]
I prefer Telegram, but yes. I have discord. Give ur one, I will add you

**Comment by juvian** [comment]
Juvian#4369

**Comment by HelloWorldAndEveryone** [comment]
I can't find you :(

**Comment by HelloWorldAndEveryone** [comment]
RandomNick #3162 try me

**Comment by HelloWorldAndEveryone** [comment]
Oops forgot to close the issue!
It's working now
Solution is:
1)Make as said juvian #72 
2)Open ports or use VPS

**Comment by DreiMasken** [comment]
hey, can you guys help me this time, i've been listening to what you two are doing, but i'm still not successful

**Comment by juvian** [comment]
what does that mean? can't run program, can't get eurobattle to show game, can't join the game...
Should probably show the logs as well

**Comment by DreiMasken** [comment]
everything is smooth, can login, the bot appears on the server, creates a room, but does not appear in the lobby

**Comment by juvian** [comment]
That's usually not open ports check https://ismyportopen.com/. Don't remember which port wc3 used though

**Comment by DreiMasken** [comment]
yea,ports is closed 
6112

**Comment by DreiMasken** [comment]
[aura log bot.txt](https://github.com/Josko/aura-bot/files/9592298/aura.log.bot.txt)

**Comment by juvian** [comment]
If port is closed then no one can join room bot makes. Some homes have no way of opening ports, setup depends on router and internet service

**Comment by DreiMasken** [comment]
oh no, that's sad, so you can't help me?, even though I'm playing on a personal pc, is there no other way?

**Comment by juvian** [comment]
https://portforward.com/warcraft-iii/
