### ISSUE TITLE
!reload doesn't work

### ISSUE THREAD

**Issue by sfarmani** [Josko/aura-bot#86]
hello, I am trying to add a root admin to my aura.cfg file. i added the names of players to the config file as it states, with a space between each name. I then try to reload the config file while the bot is still up by typing !reload. it states that it reloaded the config file, but the root admin added cannot give any commands by whispering the bot.

Am I mistaken about what !reload does? Am I using it wrong?

Same with changing a mapcfg file. If i change it, the !reload command doesn't do anything.

**Comment by Josko** [comment]
Hello,

the `!reload` command reloads only "easy" parts, and for instance not the root admins list you mentioned. For more information see here:
https://github.com/Josko/aura-bot/blob/master/src/aura.cpp#L677 

Regarding mapcfg, you will need to (re)`load` that particular file, `!reload` only "loads" the bot configuration file (aura.cfg), and no map or other cfg file.

NB: To clarify, root admins are a setting of a particular BNET object and currently the (lackluster) design only accepts ie. the root admin list at construction, it would mean pretty much an effective restart anyway (killing the connection, deleting the object, reconstructing with new setting and reconnecting).

OTOH map configuration has nothing to do with that particular command.

**Comment by sfarmani** [comment]
I see!

Thank you for the clarification. That makes a lot of sense!
